// 100+ Curated LKG Seed Questions
export const LKG_QUESTIONS = [
  // --- COUNTING 1 to 20 ---
  {
    id: 'lkg-cnt-01',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'easy',
    questionText: 'How many red apples are there?',
    narrationText: 'How many red apples are there? Tap and count them!',
    visualData: { type: 'emojis', items: ['🍎', '🍎', '🍎'] },
    options: ['2', '3', '4'],
    correctAnswer: '3',
    explanation: 'There are 1, 2, 3 delicious red apples! 🍎',
    hint: 'Point your finger and count: 1, 2, 3!',
    points: 10,
    visualHint: ['🍎', '🍎', '🍎'],
  },
  {
    id: 'lkg-cnt-02',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'easy',
    questionText: 'Count the cute puppies! 🐶',
    narrationText: 'How many cute puppies do you see?',
    visualData: { type: 'emojis', items: ['🐶', '🐶', '🐶', '🐶'] },
    options: ['3', '4', '5'],
    correctAnswer: '4',
    explanation: '1, 2, 3, 4 playful puppies! Woof! 🐶',
    hint: 'Count each puppy one by one!',
    points: 10,
  },
  {
    id: 'lkg-cnt-03',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'easy',
    questionText: 'How many bright stars are shining? ⭐',
    narrationText: 'How many bright stars are shining in the sky?',
    visualData: { type: 'emojis', items: ['⭐', '⭐', '⭐', '⭐', '⭐'] },
    options: ['4', '5', '6'],
    correctAnswer: '5',
    explanation: '5 sparkling stars shining bright! ⭐',
    hint: 'Count the stars with your finger: 1, 2, 3, 4, 5!',
    points: 10,
  },
  {
    id: 'lkg-cnt-04',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'easy',
    questionText: 'How many yummy bananas? 🍌',
    narrationText: 'How many yummy bananas are here?',
    visualData: { type: 'emojis', items: ['🍌', '🍌'] },
    options: ['1', '2', '3'],
    correctAnswer: '2',
    explanation: 'There are 2 sweet bananas! 🍌',
    hint: 'One, two bananas!',
    points: 10,
  },
  {
    id: 'lkg-cnt-05',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'medium',
    questionText: 'How many butterflies are fluttering? 🦋',
    narrationText: 'Count the beautiful butterflies.',
    visualData: { type: 'emojis', items: ['🦋', '🦋', '🦋', '🦋', '🦋', '🦋'] },
    options: ['5', '6', '7'],
    correctAnswer: '6',
    explanation: 'There are 6 colorful butterflies! 🦋',
    hint: 'Count carefully: 1, 2, 3, 4, 5, 6!',
    points: 10,
  },
  {
    id: 'lkg-cnt-06',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'medium',
    questionText: 'How many buzzing bees? 🐝',
    narrationText: 'How many busy bees do you see?',
    visualData: { type: 'emojis', items: ['🐝', '🐝', '🐝', '🐝', '🐝', '🐝', '🐝'] },
    options: ['6', '7', '8'],
    correctAnswer: '7',
    explanation: '7 busy bees making sweet honey! 🐝',
    hint: 'Count past six: one more is seven!',
    points: 10,
  },
  {
    id: 'lkg-cnt-07',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'medium',
    questionText: 'How many colorful balloons? 🎈',
    narrationText: 'Count all the party balloons!',
    visualData: { type: 'emojis', items: ['🎈', '🎈', '🎈', '🎈', '🎈', '🎈', '🎈', '🎈'] },
    options: ['7', '8', '9'],
    correctAnswer: '8',
    explanation: 'There are 8 festive balloons! 🎈',
    hint: 'Count: 1, 2, 3, 4, 5, 6, 7, 8!',
    points: 10,
  },
  {
    id: 'lkg-cnt-08',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'medium',
    questionText: 'How many juicy strawberries? 🍓',
    narrationText: 'How many sweet red strawberries are in the basket?',
    visualData: { type: 'emojis', items: ['🍓', '🍓', '🍓', '🍓', '🍓', '🍓', '🍓', '🍓', '🍓'] },
    options: ['8', '9', '10'],
    correctAnswer: '9',
    explanation: 'Yum! There are 9 juicy strawberries! 🍓',
    hint: 'Almost ten! It is one less than ten.',
    points: 10,
  },
  {
    id: 'lkg-cnt-09',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'hard',
    questionText: 'Count the shiny blue diamonds! 💎',
    narrationText: 'Count all the shiny diamonds.',
    visualData: { type: 'emojis', items: ['💎', '💎', '💎', '💎', '💎', '💎', '💎', '💎', '💎', '💎'] },
    options: ['9', '10', '11'],
    correctAnswer: '10',
    explanation: 'A whole bunch of 10 shiny diamonds! 💎',
    hint: 'Both hands full of fingers: 10!',
    points: 10,
  },
  {
    id: 'lkg-cnt-10',
    grade: 'lkg',
    category: 'counting',
    questionType: 'visual-counting',
    difficulty: 'hard',
    questionText: 'How many friendly frogs on lily pads? 🐸',
    narrationText: 'Count the green frogs.',
    visualData: { type: 'emojis', items: ['🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸', '🐸'] },
    options: ['11', '12', '13'],
    correctAnswer: '12',
    explanation: 'Ribbit! There are 12 jumping frogs! 🐸',
    hint: 'Ten plus two more makes 12!',
    points: 10,
  },

  // --- NUMBER RECOGNITION & BIGGER / SMALLER ---
  {
    id: 'lkg-num-01',
    grade: 'lkg',
    category: 'numbers',
    questionType: 'bigger-smaller',
    difficulty: 'easy',
    questionText: 'Which number is BIGGER?',
    narrationText: 'Which number is bigger? 7 or 4?',
    visualData: { type: 'cards', items: ['7', '4'] },
    options: ['7', '4'],
    correctAnswer: '7',
    explanation: '7 is greater than 4! 7 has more items! 🎈',
    hint: 'Think: which number has more toys?',
    points: 10,
  },
  {
    id: 'lkg-num-02',
    grade: 'lkg',
    category: 'numbers',
    questionType: 'bigger-smaller',
    difficulty: 'easy',
    questionText: 'Which number is SMALLER?',
    narrationText: 'Which number is smaller? 3 or 8?',
    visualData: { type: 'cards', items: ['3', '8'] },
    options: ['3', '8'],
    correctAnswer: '3',
    explanation: '3 is smaller than 8! 3 is fewer items! 🍭',
    hint: 'Which number comes first when we count 1, 2, 3...?',
    points: 10,
  },
  {
    id: 'lkg-num-03',
    grade: 'lkg',
    category: 'numbers',
    questionType: 'missing-number',
    difficulty: 'easy',
    questionText: 'What number comes next? 1, 2, 3, ?',
    narrationText: 'What number comes next? 1, 2, 3, and then?',
    visualData: { type: 'cards', items: ['1', '2', '3', '❓'] },
    options: ['4', '5', '6'],
    correctAnswer: '4',
    explanation: '1, 2, 3, 4! Four comes right after three! 🎉',
    hint: 'Sing the counting song: 1, 2, 3... four!',
    points: 10,
  },
  {
    id: 'lkg-num-04',
    grade: 'lkg',
    category: 'numbers',
    questionType: 'missing-number',
    difficulty: 'medium',
    questionText: 'Find the missing number: 3, 4, ?, 6',
    narrationText: 'Find the missing number in the line: 3, 4, blank, 6.',
    visualData: { type: 'cards', items: ['3', '4', '❓', '6'] },
    options: ['2', '5', '7'],
    correctAnswer: '5',
    explanation: '3, 4, 5, 6! 5 fits perfectly in the middle! 🌈',
    hint: 'What comes right after four?',
    points: 10,
  },
  {
    id: 'lkg-num-05',
    grade: 'lkg',
    category: 'numbers',
    questionType: 'bigger-smaller',
    difficulty: 'easy',
    questionText: 'Which group has MORE fish? 🐟',
    narrationText: 'Which group has more fish? 4 fish or 2 fish?',
    visualData: { type: 'cards', items: ['🐟🐟🐟🐟', '🐟🐟'] },
    options: ['4 Fish', '2 Fish'],
    correctAnswer: '4 Fish',
    explanation: '4 fish is more than 2 fish! 🌊',
    hint: 'Count the fish in each group.',
    points: 10,
  },

  // --- PICTURE ADDITION ---
  {
    id: 'lkg-add-01',
    grade: 'lkg',
    category: 'addition',
    questionType: 'picture-addition',
    difficulty: 'easy',
    questionText: '🍎🍎 + 🍎🍎🍎 = ?',
    narrationText: '2 apples plus 3 apples makes how many apples altogether?',
    visualData: { type: 'emojis', items: ['🍎🍎', '+', '🍎🍎🍎'], countA: 2, countB: 3, emojiA: '🍎' },
    options: ['4', '5', '6'],
    correctAnswer: '5',
    explanation: '2 apples and 3 apples together make 5 apples! 🍎🍎🍎🍎🍎',
    hint: 'Put them together and count all of them: 1, 2, 3, 4, 5!',
    points: 10,
  },
  {
    id: 'lkg-add-02',
    grade: 'lkg',
    category: 'addition',
    questionType: 'picture-addition',
    difficulty: 'easy',
    questionText: '⭐ + ⭐ = ?',
    narrationText: '1 star plus 1 star equals how many stars?',
    visualData: { type: 'emojis', items: ['⭐', '+', '⭐'], countA: 1, countB: 1, emojiA: '⭐' },
    options: ['1', '2', '3'],
    correctAnswer: '2',
    explanation: '1 plus 1 equals 2! Double stars! ⭐⭐',
    hint: 'Count both stars together.',
    points: 10,
  },
  {
    id: 'lkg-add-03',
    grade: 'lkg',
    category: 'addition',
    questionType: 'picture-addition',
    difficulty: 'easy',
    questionText: '🚗🚗🚗 + 🚗 = ?',
    narrationText: '3 toy cars plus 1 toy car equals how many?',
    visualData: { type: 'emojis', items: ['🚗🚗🚗', '+', '🚗'], countA: 3, countB: 1, emojiA: '🚗' },
    options: ['3', '4', '5'],
    correctAnswer: '4',
    explanation: '3 cars plus 1 more car gives 4 zoomy cars! 🚗🚗🚗🚗',
    hint: 'Start at three and count one more: 4!',
    points: 10,
  },
  {
    id: 'lkg-add-04',
    grade: 'lkg',
    category: 'addition',
    questionType: 'picture-addition',
    difficulty: 'medium',
    questionText: '🌸🌸 + 🌸🌸 = ?',
    narrationText: '2 flowers plus 2 flowers equals how many flowers?',
    visualData: { type: 'emojis', items: ['🌸🌸', '+', '🌸🌸'], countA: 2, countB: 2, emojiA: '🌸' },
    options: ['3', '4', '5'],
    correctAnswer: '4',
    explanation: '2 flowers plus 2 flowers make a pretty bunch of 4 flowers! 🌸',
    hint: 'Count: 1, 2, 3, 4!',
    points: 10,
  },
  {
    id: 'lkg-add-05',
    grade: 'lkg',
    category: 'addition',
    questionType: 'picture-addition',
    difficulty: 'medium',
    questionText: '🎈🎈🎈 + 🎈🎈 = ?',
    narrationText: '3 balloons plus 2 balloons equals how many?',
    visualData: { type: 'emojis', items: ['🎈🎈🎈', '+', '🎈🎈'], countA: 3, countB: 2, emojiA: '🎈' },
    options: ['4', '5', '6'],
    correctAnswer: '5',
    explanation: '3 balloons plus 2 balloons make 5 balloons! 🎈🎈🎈🎈🎈',
    hint: 'Count 3, then 4, 5!',
    points: 10,
  },

  // --- PICTURE SUBTRACTION ---
  {
    id: 'lkg-sub-01',
    grade: 'lkg',
    category: 'subtraction',
    questionType: 'picture-subtraction',
    difficulty: 'easy',
    questionText: '🐟🐟🐟🐟🐟 (5 fish) - 2 swim away. How many left?',
    narrationText: 'There were 5 fish in the pond. 2 fish swam away. How many fish are left?',
    visualData: { type: 'emojis', items: ['🐟', '🐟', '🐟', '❌', '❌'], countA: 5, subtractionCrossCount: 2, emojiA: '🐟' },
    options: ['2', '3', '4'],
    correctAnswer: '3',
    explanation: '5 fish minus 2 that swam away leaves 3 fish! 🐟🐟🐟',
    hint: 'Cross out two fish and count the remaining ones: 1, 2, 3!',
    points: 10,
  },
  {
    id: 'lkg-sub-02',
    grade: 'lkg',
    category: 'subtraction',
    questionType: 'picture-subtraction',
    difficulty: 'easy',
    questionText: '🧁🧁🧁 (3 cupcakes) - 1 eaten. How many left?',
    narrationText: 'You had 3 cupcakes and ate 1. How many cupcakes are left?',
    visualData: { type: 'emojis', items: ['🧁', '🧁', '❌'], countA: 3, subtractionCrossCount: 1, emojiA: '🧁' },
    options: ['1', '2', '3'],
    correctAnswer: '2',
    explanation: '3 cupcakes take away 1 leaves 2 yummy cupcakes! 🧁🧁',
    hint: 'Take one away: one, two are left!',
    points: 10,
  },
  {
    id: 'lkg-sub-03',
    grade: 'lkg',
    category: 'subtraction',
    questionType: 'picture-subtraction',
    difficulty: 'medium',
    questionText: '🎈🎈🎈🎈 (4 balloons) - 1 popped! How many left?',
    narrationText: '4 balloons, but 1 popped! How many are still floating?',
    visualData: { type: 'emojis', items: ['🎈', '🎈', '🎈', '💥'], countA: 4, subtractionCrossCount: 1, emojiA: '🎈' },
    options: ['2', '3', '4'],
    correctAnswer: '3',
    explanation: '4 balloons take away 1 leaves 3 floating balloons! 🎈🎈🎈',
    hint: 'Count the balloons that did not pop.',
    points: 10,
  },

  // --- SHAPES & PATTERNS ---
  {
    id: 'lkg-shp-01',
    grade: 'lkg',
    category: 'shapes',
    questionType: 'shape-recognition',
    difficulty: 'easy',
    questionText: 'Which one is a TRIANGLE? 📐',
    narrationText: 'Which shape is a triangle with 3 sides? Triangle!',
    visualData: { type: 'cards', items: ['🔴 Circle', '🔺 Triangle', '🟦 Square'] },
    options: ['Circle', 'Triangle', 'Square'],
    correctAnswer: 'Triangle',
    explanation: 'A triangle has 3 sharp corners and 3 sides! 🔺',
    hint: 'Look for the shape that looks like a slice of pizza or mountain top!',
    points: 10,
  },
  {
    id: 'lkg-shp-02',
    grade: 'lkg',
    category: 'shapes',
    questionType: 'shape-recognition',
    difficulty: 'easy',
    questionText: 'Which shape is perfectly ROUND like a ball? ⚽',
    narrationText: 'Which shape is round with no straight corners? A circle!',
    visualData: { type: 'cards', items: ['⭕ Circle', '⏹️ Square', '🔺 Triangle'] },
    options: ['Circle', 'Square', 'Triangle'],
    correctAnswer: 'Circle',
    explanation: 'A circle is completely round like a wheel or coin! ⭕',
    hint: 'It rolls and has no corners!',
    points: 10,
  },
  {
    id: 'lkg-pat-01',
    grade: 'lkg',
    category: 'patterns',
    questionType: 'pattern',
    difficulty: 'easy',
    questionText: 'What comes next in the pattern? 🍎 🍌 🍎 🍌 ❓',
    narrationText: 'Look at the pattern: Apple, Banana, Apple, Banana. What comes next?',
    visualData: { type: 'emojis', items: ['🍎', '🍌', '🍎', '🍌', '❓'] },
    options: ['🍎 Apple', '🍌 Banana', '🍇 Grapes'],
    correctAnswer: '🍎 Apple',
    explanation: 'Apple, Banana, Apple, Banana... then Apple comes next! 🍎',
    hint: 'Say it out loud: Apple, Banana, Apple, Banana... ?',
    points: 10,
  },
  {
    id: 'lkg-pat-02',
    grade: 'lkg',
    category: 'patterns',
    questionType: 'pattern',
    difficulty: 'easy',
    questionText: 'What comes next? ⭐ 🔵 ⭐ 🔵 ❓',
    narrationText: 'Star, Circle, Star, Circle. What is next?',
    visualData: { type: 'emojis', items: ['⭐', '🔵', '⭐', '🔵', '❓'] },
    options: ['⭐ Star', '🔵 Circle', '🟩 Square'],
    correctAnswer: '⭐ Star',
    explanation: 'Star comes right after Circle in this repeating sequence! ⭐',
    hint: 'After blue circle, we go back to the yellow star!',
    points: 10,
  },
  {
    id: 'lkg-odd-01',
    grade: 'lkg',
    category: 'logic',
    questionType: 'odd-one-out',
    difficulty: 'easy',
    questionText: 'Which one is DIFFERENT from the others? 🐶 🐶 🐱 🐶',
    narrationText: 'Which animal is different from the others? Spot the odd one out!',
    visualData: { type: 'emojis', items: ['🐶', '🐶', '🐱', '🐶'] },
    options: ['🐱 Cat', '🐶 Dog'],
    correctAnswer: '🐱 Cat',
    explanation: 'The cat is different because the other three are dogs! Meow! 🐱',
    hint: 'Look closely at the third friend.',
    points: 10,
  },
  {
    id: 'lkg-pos-01',
    grade: 'lkg',
    category: 'position',
    questionType: 'position',
    difficulty: 'easy',
    questionText: 'Where is the bird? 🐦 (Above the tree 🌳)',
    narrationText: 'Where is the bird? Is it above or under the tree?',
    visualData: { type: 'emojis', items: ['🐦 (in sky)', '🌳 (on ground)'] },
    options: ['Above the tree', 'Under the tree', 'Inside the trunk'],
    correctAnswer: 'Above the tree',
    explanation: 'The bird is flying high above the green tree! 🌤️',
    hint: 'Look up in the sky!',
    points: 10,
  },
  {
    id: 'lkg-mem-01',
    grade: 'lkg',
    category: 'memory',
    questionType: 'memory',
    difficulty: 'easy',
    questionText: 'Remember these 3 items: 🍎 🐱 🚗. Which one was there?',
    narrationText: 'Remember these items: Apple, Cat, and Car. Which one did you see?',
    visualData: { type: 'memory-items', memoryDisplaySeconds: 4, items: ['🍎 Apple', '🐱 Cat', '🚗 Car'] },
    options: ['🐱 Cat', '🐘 Elephant', '🚀 Rocket'],
    correctAnswer: '🐱 Cat',
    explanation: 'Awesome memory! You remembered the cute cat! 🐱',
    hint: 'One of the animals was saying meow!',
    points: 10,
  },

  // Dynamic curated pool to reach 100+ LKG questions
  ...Array.from({ length: 85 }).map((_, i) => {
    const num = i + 1;
    const catIndex = i % 5;
    if (catIndex === 0) {
      const count = (i % 9) + 2;
      const emoji = ['🎈', '🍭', '⭐', '🚗', '🐱', '🍎', '🐟', '🌻', '🧁', '⚽'][i % 10];
      const items = Array.from({ length: count }, () => emoji);
      return {
        id: `lkg-gen-c-${num}`,
        grade: 'lkg',
        category: 'counting',
        questionType: 'visual-counting',
        difficulty: count <= 4 ? 'easy' : count <= 7 ? 'medium' : 'hard',
        questionText: `How many ${emoji} can you count?`,
        narrationText: `Count the items. How many are there?`,
        visualData: { type: 'emojis', items },
        options: [String(count), String(count + 1), String(Math.max(1, count - 1))],
        correctAnswer: String(count),
        explanation: `There are ${count} ${emoji} in total! Great counting! ✨`,
        hint: `Touch each one with your finger and count from 1!`,
        points: 10,
      };
    } else if (catIndex === 1) {
      const a = (i % 3) + 1;
      const b = ((i + 1) % 3) + 1;
      const sum = a + b;
      const emoji = ['🍓', '🌸', '🐥', '🧸', '🍬', '🍩'][i % 6];
      return {
        id: `lkg-gen-a-${num}`,
        grade: 'lkg',
        category: 'addition',
        questionType: 'picture-addition',
        difficulty: sum <= 4 ? 'easy' : 'medium',
        questionText: `${emoji.repeat(a)} + ${emoji.repeat(b)} = ?`,
        narrationText: `${a} plus ${b} equals how many?`,
        visualData: { type: 'emojis', items: [emoji.repeat(a), '+', emoji.repeat(b)], countA: a, countB: b, emojiA: emoji },
        options: [String(sum), String(sum + 1), String(Math.max(1, sum - 1))],
        correctAnswer: String(sum),
        explanation: `${a} plus ${b} makes ${sum} in total! 🌟`,
        hint: `Count the first group, then keep counting the second group!`,
        points: 10,
      };
    } else if (catIndex === 2) {
      const a = (i % 4) + 2;
      const b = (i % (a - 1)) + 1;
      const diff = a - b;
      const emoji = ['🐟', '🧁', '🍎', '🎈', '🍪'][i % 5];
      return {
        id: `lkg-gen-s-${num}`,
        grade: 'lkg',
        category: 'subtraction',
        questionType: 'picture-subtraction',
        difficulty: diff <= 2 ? 'easy' : 'medium',
        questionText: `${emoji.repeat(a)} - ${b} taken away = ?`,
        narrationText: `You have ${a} and take away ${b}. How many are left?`,
        visualData: { type: 'emojis', items: [...Array(diff).fill(emoji), ...Array(b).fill('❌')], countA: a, subtractionCrossCount: b, emojiA: emoji },
        options: [String(diff), String(diff + 1), String(Math.max(0, diff - 1))],
        correctAnswer: String(diff),
        explanation: `${a} take away ${b} leaves ${diff}! Well done! 🎉`,
        hint: `Cross out ${b} of them and count what remains!`,
        points: 10,
      };
    } else if (catIndex === 3) {
      const n1 = (i % 8) + 1;
      const n2 = ((i + 3) % 8) + 1;
      const val1 = Math.max(n1, n2);
      const val2 = Math.min(n1, n2);
      const askBigger = i % 2 === 0;
      const correct = askBigger ? String(val1) : String(val2);
      return {
        id: `lkg-gen-n-${num}`,
        grade: 'lkg',
        category: 'numbers',
        questionType: 'bigger-smaller',
        difficulty: 'easy',
        questionText: `Which number is ${askBigger ? 'BIGGER' : 'SMALLER'}?`,
        narrationText: `Which number is ${askBigger ? 'bigger' : 'smaller'}? ${val1} or ${val2}?`,
        visualData: { type: 'cards', items: [String(val1), String(val2)] },
        options: [String(val1), String(val2)],
        correctAnswer: correct,
        explanation: `${correct} is the ${askBigger ? 'bigger' : 'smaller'} number! ⭐`,
        hint: `Think which number has more pieces!`,
        points: 10,
      };
    } else {
      const pairs = [['🟡', '🟣'], ['⭐', '🌙'], ['🐶', '🐱'], ['🚗', '🚲'], ['🍎', '🍊']];
      const pair = pairs[i % pairs.length];
      return {
        id: `lkg-gen-p-${num}`,
        grade: 'lkg',
        category: 'patterns',
        questionType: 'pattern',
        difficulty: 'easy',
        questionText: `What comes next? ${pair[0]} ${pair[1]} ${pair[0]} ${pair[1]} ❓`,
        narrationText: `What comes next in this pattern?`,
        visualData: { type: 'emojis', items: [pair[0], pair[1], pair[0], pair[1], '❓'] },
        options: [pair[0], pair[1], '💎'],
        correctAnswer: pair[0],
        explanation: `${pair[0]} comes right after ${pair[1]} in this repeating pattern! 🌈`,
        hint: `Read the pattern rhythm out loud!`,
        points: 10,
      };
    }
  }),
];
