// 10 Themed Adventure Worlds
export const WORLDS = [
  {
    id: 'number-land',
    order: 1,
    title: 'Number Land',
    subtitle: 'Counting & Number Magic',
    emoji: '🔢',
    themeColor: '#FF7A00',
    gradient: 'linear-gradient(135deg, #f59e0b, #ea580c)',
    category: 'counting',
    levelsCount: 5,
  },
  {
    id: 'addition-forest',
    order: 2,
    title: 'Addition Forest',
    subtitle: 'Combining & Growing Together',
    emoji: '🌲',
    themeColor: '#10b981',
    gradient: 'linear-gradient(135deg, #10b981, #059669)',
    category: 'addition',
    levelsCount: 5,
  },
  {
    id: 'subtraction-valley',
    order: 3,
    title: 'Subtraction Valley',
    subtitle: 'Taking Away & Finding Remaining',
    emoji: '🌊',
    themeColor: '#0284c7',
    gradient: 'linear-gradient(135deg, #0284c7, #2563eb)',
    category: 'subtraction',
    levelsCount: 5,
  },
  {
    id: 'shape-kingdom',
    order: 4,
    title: 'Shape Kingdom',
    subtitle: 'Circles, Triangles & Magical Forms',
    emoji: '🏰',
    themeColor: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    category: 'shapes',
    levelsCount: 5,
  },
  {
    id: 'pattern-planet',
    order: 5,
    title: 'Pattern Planet',
    subtitle: 'Repeating Colors & Cosmic Rhythms',
    emoji: '🪐',
    themeColor: '#ec4899',
    gradient: 'linear-gradient(135deg, #ec4899, #db2777)',
    category: 'patterns',
    levelsCount: 5,
  },
  {
    id: 'logic-castle',
    order: 6,
    title: 'Logic Castle',
    subtitle: 'Odd One Out & Brain Riddles',
    emoji: '🧩',
    themeColor: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #d97706)',
    category: 'logic',
    levelsCount: 5,
  },
  {
    id: 'memory-island',
    order: 7,
    title: 'Memory Island',
    subtitle: 'Quick Eyes & Super Recall',
    emoji: '🏝️',
    themeColor: '#14b8a6',
    gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)',
    category: 'memory',
    levelsCount: 5,
  },
  {
    id: 'reasoning-galaxy',
    order: 8,
    title: 'Reasoning Galaxy',
    subtitle: 'Directions, Space & Positions',
    emoji: '🌌',
    themeColor: '#6366f1',
    gradient: 'linear-gradient(135deg, #6366f1, #4f46e5)',
    category: 'position',
    levelsCount: 5,
  },
  {
    id: 'speed-challenge',
    order: 9,
    title: 'Speed Challenge',
    subtitle: 'Gentle Fun & Quick Fire Math',
    emoji: '⚡',
    themeColor: '#eab308',
    gradient: 'linear-gradient(135deg, #eab308, #ca8a04)',
    category: 'numbers',
    levelsCount: 5,
  },
  {
    id: 'grand-olympiad',
    order: 10,
    title: 'Grand Olympiad',
    subtitle: 'The Ultimate Explorer Championship',
    emoji: '🏆',
    themeColor: '#ef4444',
    gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    category: 'word-problems',
    levelsCount: 5,
  },
];
